### ISSUE TITLE
OTRS Sag1029243 — Dropdown i avanceret søgning i REX skal fjernes (til TJAN)

### ISSUE THREAD

**Issue by tja1607** [Det-Kongelige-Bibliotek/rex#4]
Hey Tom,
Dropdownmenuen i den avancerede søgning i REX (AND,OR) skal fjernes helt nu. Det viser sig, at den ikke virker korrekt endnu, så vi må afvente, at ExLibris får det løst inden vi igen kan sætte den ind.

Hilsner
Karen

**Comment by O-Zone** [comment]
Den her er vist forældet! :-O
